import { Survey, Question } from '../types/survey';

export const SEED_SURVEYS: Survey[] = [
  {
    id: 'survey-danang-student-lifestyle',
    title: 'Da Nang Student Lifestyle Survey',
    description: 'Comprehensive research on living conditions, transit, expenditure, and campus satisfaction across Da Nang universities.',
    topic: 'Student Lifestyle & Social Research',
    status: 'active',
    createdAt: new Date('2026-03-01T08:00:00Z').toISOString(),
    updatedAt: new Date('2026-03-01T08:00:00Z').toISOString(),
  },
  {
    id: 'survey-campus-facility-inspection',
    title: 'Campus Facility & Infrastructure Inspection',
    description: 'Field inspection and condition audit for university lecture halls, computer labs, electrical facilities, and student spaces.',
    topic: 'Facility Inspection & Audit',
    status: 'active',
    createdAt: new Date('2026-03-01T09:00:00Z').toISOString(),
    updatedAt: new Date('2026-03-01T09:00:00Z').toISOString(),
  },
];

export const SEED_QUESTIONS: Question[] = [
  // --- Da Nang Student Lifestyle Survey Questions (8 questions) ---
  {
    id: 'q-dn-1',
    surveyId: 'survey-danang-student-lifestyle',
    order: 1,
    question: 'What is your current age?',
    type: 'number',
    required: true,
    min: 17,
    max: 60,
    placeholder: 'e.g. 21',
  },
  {
    id: 'q-dn-2',
    surveyId: 'survey-danang-student-lifestyle',
    order: 2,
    question: 'What is your gender?',
    type: 'singleChoice',
    required: true,
    options: ['Male', 'Female', 'Non-binary', 'Prefer not to say'],
  },
  {
    id: 'q-dn-3',
    surveyId: 'survey-danang-student-lifestyle',
    order: 3,
    question: 'Which university do you attend in Da Nang?',
    type: 'singleChoice',
    required: true,
    options: [
      'University of Science and Technology (DUT)',
      'University of Economics (DUE)',
      'University of Science and Education (UED)',
      'University of Foreign Language Studies (UFL)',
      'Vietnam-Korea University of ICT (VKU)',
      'FPT University Da Nang',
      'Duy Tan University (DTU)',
      'Other',
    ],
  },
  {
    id: 'q-dn-4',
    surveyId: 'survey-danang-student-lifestyle',
    order: 4,
    question: 'Which urban district or area do you reside in?',
    type: 'singleChoice',
    required: true,
    options: ['Hai Chau', 'Thanh Khe', 'Son Tra', 'Ngu Hanh Son', 'Lien Chieu', 'Cam Le', 'Hoa Vang'],
  },
  {
    id: 'q-dn-5',
    surveyId: 'survey-danang-student-lifestyle',
    order: 5,
    question: 'What is your primary transportation method for commuting?',
    type: 'singleChoice',
    required: true,
    options: ['Motorbike', 'Electric Bicycle / Scooter', 'Public DanangBus', 'Bicycle', 'Walking', 'Ride-hailing (Grab/Be/XanhSM)'],
  },
  {
    id: 'q-dn-6',
    surveyId: 'survey-danang-student-lifestyle',
    order: 6,
    question: 'Estimated monthly living expenses (in VND Millions)?',
    type: 'number',
    required: true,
    min: 1,
    max: 50,
    step: 0.5,
    placeholder: 'e.g. 4.5',
  },
  {
    id: 'q-dn-7',
    surveyId: 'survey-danang-student-lifestyle',
    order: 7,
    question: 'How satisfied are you with public transit & campus amenities?',
    type: 'rating',
    required: true,
    max: 5,
  },
  {
    id: 'q-dn-8',
    surveyId: 'survey-danang-student-lifestyle',
    order: 8,
    question: 'Any additional observations, recommendations, or comments?',
    type: 'longText',
    required: false,
    placeholder: 'Share your thoughts or observations about student life...',
  },

  // --- Campus Facility Inspection Questions (VKU Official Requirements) ---
  {
    id: 'q-fac-1',
    surveyId: 'survey-campus-facility-inspection',
    order: 1,
    question: 'Building',
    type: 'singleChoice',
    required: true,
    options: ['Building A - Administration', 'Building B - Tech Labs', 'Building C - Lecture Halls', 'Building D - Library', 'Sports Complex', 'Student Dormitory'],
  },
  {
    id: 'q-fac-2',
    surveyId: 'survey-campus-facility-inspection',
    order: 2,
    question: 'Floor',
    type: 'singleChoice',
    required: true,
    options: ['Ground Floor', '1st Floor', '2nd Floor', '3rd Floor', '4th Floor', '5th Floor', 'Rooftop / Basement'],
  },
  {
    id: 'q-fac-3',
    surveyId: 'survey-campus-facility-inspection',
    order: 3,
    question: 'Room #',
    type: 'shortText',
    required: true,
    placeholder: 'e.g. Room B302 or Hallway 2F',
  },
  {
    id: 'q-fac-4',
    surveyId: 'survey-campus-facility-inspection',
    order: 4,
    question: 'Category',
    type: 'singleChoice',
    required: true,
    options: ['Hardware', 'Projector', 'AC', 'Electrical', 'Furniture'],
  },
  {
    id: 'q-fac-5',
    surveyId: 'survey-campus-facility-inspection',
    order: 5,
    question: 'Condition Rating (1–5 Stars)',
    type: 'rating',
    required: true,
    max: 5,
  },
  {
    id: 'q-fac-6',
    surveyId: 'survey-campus-facility-inspection',
    order: 6,
    question: 'Defect Notes',
    type: 'longText',
    required: true,
    placeholder: 'Describe damage, wear, malfunctioning parts or maintenance needs...',
  },
  {
    id: 'q-fac-7',
    surveyId: 'survey-campus-facility-inspection',
    order: 7,
    question: 'Camera Photo Evidence',
    type: 'photo',
    required: false,
  },
];
